spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    #初始化工程时需要配置为always
    initialization-mode: never
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true
